#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

my_json:
    path: /json
    controller: App\Controller\FirstController::myJson
